# Generated by Django 3.1.7 on 2021-06-11 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Check Phone no.', regex='^[6-9]{1}[0-9]{9}$')])),
                ('child_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('THREE_TO_SEVEN', '3 to 7 years'), ('SEVEN_TO_TWELVE', '7 to 12 years')], max_length=100, null=True)),
                ('batch', models.CharField(blank=True, choices=[('MORNING', '8 to 11 am'), ('NOON', '12 to 4 am'), ('EVENING', '6 to 9 am')], max_length=100, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('utm_source', models.CharField(max_length=40, null=True)),
                ('utm_medium', models.CharField(max_length=40, null=True)),
                ('utm_campaign', models.CharField(max_length=40, null=True)),
                ('parent_company', models.CharField(max_length=200)),
            ],
        ),
    ]
