# Generated by Django 3.1.7 on 2021-06-11 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
