# Generated by Django 3.1.7 on 2021-05-04 06:12

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=payment.models.create_transaction_id, max_length=20, primary_key=True, serialize=False)),
                ('orderproduct_id', models.CharField(max_length=200)),
                ('rp_order', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('fail', 'fail'), ('initiated', 'initiated')], default='paid', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
