# Generated by Django 3.1.7 on 2021-05-04 18:21

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=payment.models.create_transaction_id, max_length=200, primary_key=True, serialize=False),
        ),
    ]
