# Generated by Django 3.1.7 on 2021-05-21 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_popularproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproducts',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popular', to='shop.products'),
        ),
    ]
